version: '3.9'
services:
  server:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  client:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_API_URI=http://localhost:8080
    ports:
      - "3000:3000"
