spring:
  application:
    name: recommendation_system_backend
  mustache.check-template-location: false
cors:
  allow-credentials: true
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:80
    - http://localhost
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - '*'
  exposed-headers:
    - Content-Disposition
server:
  port: ${SERVER_PORT:8080}
